### ISSUE TITLE
First-screen issue

### ISSUE THREAD

**Issue by ghost** [dgraziotin/openpomo#3]
After the installation, in the settings screen, the textbox claims to go to the second tab, but no tabs are shown.
(Motorola Milestone)

**Comment by dgraziotin** [comment]
Thank you for reporting this. I think there will be a general UI re-design for the next release, for a better usability. After the installation the user won't be brought to the Preferences, but directly to an Inventory Sheet

**Comment by dgraziotin** [comment]
This is fixed and will be there in the forthcoming release v0.8.0
